######################################################################
# Automatically generated by qmake (3.0) lun. janv. 16 13:00:26 2017
######################################################################

QT  += widgets serialport
TEMPLATE = app
TARGET = Fenetre_arduino
INCLUDEPATH += .

# Input
HEADERS += fenetre.h \
    my_scene.h
FORMS += fenetre.ui
SOURCES += fenetre.cpp main.cpp \
    my_scene.cpp
